# =====================================================================
# 🔄 Zachytávání „poslední uživatelské teploty“ ze skutečných hlavic
# - Kdykoliv se změní cílová teplota (setpoint) na climate.*,
#   zapíšeme ji do příslušného input_number.*_user_set_temp.
# - Při startu HA provedeme inicializaci (vezmeme aktuální setpoint).
# - Důraz na robustnost: hlídáme „unknown/unavailable“ a nuly.
# =====================================================================

automation:
  # ───────────────────────────────────────────────────────────────────
  # ▶️ Přízemí – Michal (climate.prizemi_michal)
  # ───────────────────────────────────────────────────────────────────
  - id: zona_prizemi_michal_capture_setpoint
    alias: "Zóna – Přízemí Michal: zachyť změnu setpointu"
    mode: restart
    trigger:
      # Trigguj při jakékoliv změně (včetně atributů); filtrujeme v akci.
      - platform: state
        entity_id: climate.prizemi_michal
    variables:
      new_sp: "{{ state_attr('climate.prizemi_michal','temperature') | float(0) }}"
    condition:
      - condition: template
        value_template: "{{ new_sp > 0 }}"
    action:
      - service: input_number.set_value
        data:
          entity_id: input_number.zona_prizemi_michal_user_set_temp
          value: "{{ new_sp }}"

  - id: zona_prizemi_michal_init_on_start
    alias: "Zóna – Přízemí Michal: init helperu po startu"
    mode: single
    trigger:
      - platform: homeassistant
        event: start
    action:
      # počkej chvilku, ať se climate stihne načíst
      - delay: "00:00:05"
      - variables:
          sp: "{{ state_attr('climate.prizemi_michal','temperature') | float(22.0) }}"
      - service: input_number.set_value
        data:
          entity_id: input_number.zona_prizemi_michal_user_set_temp
          value: "{{ sp }}"

  # ───────────────────────────────────────────────────────────────────
  # ▶️ 1. patro – Kuchyň (climate.1p_jidelna)
  # ───────────────────────────────────────────────────────────────────
  - id: zona_1p_jidelna_capture_setpoint
    alias: "Zóna – 1. patro Kuchyň: zachyť změnu setpointu"
    mode: restart
    trigger:
      - platform: state
        entity_id: climate.1p_jidelna
    variables:
      new_sp: "{{ state_attr('climate.1p_jidelna','temperature') | float(0) }}"
    condition:
      - condition: template
        value_template: "{{ new_sp > 0 }}"
    action:
      - service: input_number.set_value
        data:
          entity_id: input_number.zona_1p_jidelna_user_set_temp
          value: "{{ new_sp }}"

  - id: zona_1p_jidelna_init_on_start
    alias: "Zóna – 1. patro Kuchyň: init helperu po startu"
    mode: single
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: "00:00:05"
      - variables:
          sp: "{{ state_attr('climate.1p_jidelna','temperature') | float(22.0) }}"
      - service: input_number.set_value
        data:
          entity_id: input_number.zona_1p_jidelna_user_set_temp
          value: "{{ sp }}"

  # ───────────────────────────────────────────────────────────────────
  # ▶️ 2. patro – Máma (climate.2p_mama)
  # ───────────────────────────────────────────────────────────────────
  - id: zona_2p_mama_capture_setpoint
    alias: "Zóna – 2. patro Máma: zachyť změnu setpointu"
    mode: restart
    trigger:
      - platform: state
        entity_id: climate.2p_mama
    variables:
      new_sp: "{{ state_attr('climate.2p_mama','temperature') | float(0) }}"
    condition:
      - condition: template
        value_template: "{{ new_sp > 0 }}"
    action:
      - service: input_number.set_value
        data:
          entity_id: input_number.zona_2p_mama_user_set_temp
          value: "{{ new_sp }}"

  - id: zona_2p_mama_init_on_start
    alias: "Zóna – 2. patro Máma: init helperu po startu"
    mode: single
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: "00:00:05"
      - variables:
          sp: "{{ state_attr('climate.2p_mama','temperature') | float(22.0) }}"
      - service: input_number.set_value
        data:
          entity_id: input_number.zona_2p_mama_user_set_temp
          value: "{{ sp }}"
