# =====================================================================
# Soubor   : config/heating/schedule/preferences/capture/zone_2p_mama_capture_comfort.yaml
# Modul    : Zachytávání komfortu – 2. patro (Máma)
# Účel     : Ukládání poslední uživatelsky nastavené komfortní teploty
# Autor    : Michal
# Poslední úprava : 2025-11-19
# =====================================================================

automation:
  - id: capture_last_comfort_2p_mama
    alias: "Zachytni poslední komfort – 2. patro Máma"
    mode: restart
    initial_state: true

    # Hlavice změnila setpoint → zkontroluj, zda jde o komfort a ulož
    triggers:
      - trigger: state
        entity_id: climate.2p_mama
        attribute: temperature

    variables:
      new_set: "{{ state_attr('climate.2p_mama', 'temperature') | float(0) }}"
      eco: "{{ states('input_number.eco_temp_default') | float(15) }}"

    conditions:
      # Komfort = hodnota vyšší než ECO + 0.2 °C
      - condition: template
        value_template: "{{ new_set >= (eco + 0.2) }}"

      # Uložit pouze při skutečné změně (> 0.1 °C)
      - condition: template
        value_template: >
          {{ (states('input_number.2p_mama_last_comfort') | float(0)
              - new_set) | abs > 0.1 }}

      # Při Boostu neukládat, aby se nepoškodil poslední komfort
      - condition: state
        entity_id: binary_sensor.kotel_boost_active
        state: "off"

    actions:
      - action: input_number.set_value
        target:
          entity_id: input_number.2p_mama_last_comfort
        data:
          value: "{{ new_set }}"

      - action: logbook.log
        data:
          name: "2. patro – Máma"
          message: "Uložena komfortní teplota: {{ new_set }} °C"
          entity_id: climate.2p_mama
