# =====================================================================
# 🕒 ROZVRH – 1. patro (Kuchyň) – inteligentní spouštění
# - Uvnitř okna → poslední komfortní (input_number.1p_kuchyn_last_comfort)
# - Mimo okno   → ECO (input_number.eco_temp_default)
# - Spouští se jen při změně (čas, rozvrh, ruční setpoint)
# =====================================================================

automation:
  - alias: "Rozvrh 1P Kuchyň – inteligentní spouštění"
    id: schedule_1p_kuchyn_smart
    mode: restart
    initial_state: true

    trigger:
      - platform: time
        at:
          - input_datetime.kuchyn_weekday_start
          - input_datetime.kuchyn_weekday_end
          - input_datetime.kuchyn_weekend_start
          - input_datetime.kuchyn_weekend_end
      - platform: state
        entity_id:
          - input_datetime.kuchyn_weekday_start
          - input_datetime.kuchyn_weekday_end
          - input_datetime.kuchyn_weekend_start
          - input_datetime.kuchyn_weekend_end
          - input_boolean.schedule_enable_1p_kuchyn
      - platform: state
        entity_id: climate.1_patro_kuchyn
        attribute: temperature

    variables:
      eco_temp: "{{ states('input_number.eco_temp_default') | float(18) }}"
      last_comfort: "{{ states('input_number.1p_kuchyn_last_comfort') | float(21.5) }}"

      start: >
        {% if now().isoweekday() in [1,2,3,4,5] %}
          {{ states('input_datetime.kuchyn_weekday_start') }}
        {% else %}
          {{ states('input_datetime.kuchyn_weekend_start') }}
        {% endif %}
      end: >
        {% if now().isoweekday() in [1,2,3,4,5] %}
          {{ states('input_datetime.kuchyn_weekday_end') }}
        {% else %}
          {{ states('input_datetime.kuchyn_weekend_end') }}
        {% endif %}
      now_hms: "{{ now().strftime('%H:%M:%S') }}"

      # 🧮 Jsme uvnitř okna? (řeší i přes půlnoc)
      in_window: >
        {% set s = start %}
        {% set e = end %}
        {% set n = now_hms %}
        {% if s <= e %}
          {{ s <= n < e }}
        {% else %}
          {{ (n >= s) or (n < e) }}
        {% endif %}

    condition:
      - condition: state
        entity_id: input_boolean.schedule_enable_1p_kuchyn
        state: "on"

    action:
      - choose:

          # 🟢 KOMFORTNÍ OKNO
          - conditions:
              - condition: template
                value_template: "{{ in_window }}"
            sequence:
              - service: climate.set_hvac_mode
                target: { entity_id: climate.1_patro_kuchyn }
                data: { hvac_mode: heat }
              - service: climate.set_temperature
                target: { entity_id: climate.1_patro_kuchyn }
                data:
                  temperature: "{{ last_comfort }}"
              - service: logbook.log
                data:
                  name: "Rozvrh 1P Kuchyň"
                  message: "Komfortní režim {{ last_comfort }} °C (inteligentní spuštění)"
                  entity_id: climate.1_patro_kuchyn

          - conditions:
              - condition: template
                value_template: "{{ not in_window }}"
            sequence:
              - service: climate.set_hvac_mode
                target: { entity_id: climate.1_patro_kuchyn }
                data: { hvac_mode: heat }
              - service: climate.set_temperature
                target: { entity_id: climate.1_patro_kuchyn }
                data:
                  temperature: "{{ eco_temp }}"
              - service: logbook.log
                data:
                  name: "Rozvrh 1P Kuchyň"
                  message: "ECO {{ eco_temp }} °C (inteligentní spuštění)"
                  entity_id: climate.1_patro_kuchyn

# =====================================================================
# 💾 CAPTURE – ulož poslední KOMFORT pro 1. patro (Kuchyň)
# - Uloží se POUZE hodnoty nad ECO (aby ECO nepřepsalo komfort)
# =====================================================================
  - alias: "1P Kuchyň – uložit poslední komfort"
    id: capture_1p_kuchyn_last_comfort
    mode: queued
    trigger:
      - platform: state
        entity_id: climate.1_patro_kuchyn
        attribute: temperature
    condition:
      - condition: template
        value_template: >
          {{ state_attr('climate.1_patro_kuchyn', 'temperature') | float(0)
             > (states('input_number.eco_temp_default') | float(18)) + 0.2 }}
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.1p_kuchyn_last_comfort
        data:
          value: "{{ state_attr('climate.1_patro_kuchyn', 'temperature') | float(21.5) }}"
      - service: logbook.log
        data:
          name: "1P Kuchyň"
          message: "Uložena komfortní teplota: {{ state_attr('climate.1_patro_kuchyn', 'temperature') }} °C"