blueprint:
  name: "Heating – Smart zone schedule (with comfort capture)"
  description: >
    Chytrý rozvrh pro jednu topnou zónu.
    Řídí komfort/ECO podle Scheduler booleanu a poslední komfortní teploty
    a zároveň ukládá poslední uživatelsky nastavený komfortní setpoint.
    Podporuje globální režimy: Auto / Eco / Boost / Off.
  domain: automation

  input:
    zone_name:
      name: Název zóny pro logbook
      description: Jak se má zóna jmenovat v logu (např. 'Přízemí Michal', '1P Jídelna').
      selector:
        text:

    climate_entity:
      name: Climate entity zóny
      selector:
        entity:
          domain: climate

    schedule_enable:
      name: Enable boolean pro rozvrh zóny
      selector:
        entity:
          domain: input_boolean

    scheduler_entity:
      name: Scheduler Boolean (HACS)
      description: "Helper ovládaný Schedulerem (ON = komfortní okno, OFF = mimo okno)."
      selector:
        entity:
          domain: input_boolean

    last_comfort_helper:
      name: Helper – poslední komfortní teplota (input_number)
      selector:
        entity:
          domain: input_number

    eco_temp_default:
      name: Eco teplota (input_number)
      selector:
        entity:
          domain: input_number

    boost_active:
      name: Boost aktivní (binary_sensor)
      description: "Binary sensor, který říká, že je aktivní Boost (např. binary_sensor.kotel_boost_active)."
      selector:
        entity:
          domain: binary_sensor

    cooldown_seconds:
      name: Antispam – cooldown (sekundy)
      description: "Minimální čas mezi aplikacemi rozvrhu při 'spam' triggerech (mimo scheduler trigger a mimo ruční změnu setpointu)."
      default: 20
      selector:
        number:
          min: 0
          max: 300
          step: 1
          unit_of_measurement: s

    # -----------------------------------------------------------------
    # 🧠 MANUÁLNÍ OVERRIDE – nové vstupy (priorita nad Schedulerem)
    # -----------------------------------------------------------------
    manual_override_boolean:
      name: Manuál – override aktivní (input_boolean)
      description: "ON = manuální override aktivní pro tuto zónu (má prioritu nad rozvrhem)."
      selector:
        entity:
          domain: input_boolean

    manual_override_timer:
      name: Manuál – timer override (timer)
      description: "Pokud běží (active), override je časově aktivní. Při idle/paused se ukončí."
      selector:
        entity:
          domain: timer

    manual_override_type:
      name: Manuál – typ ukončení (input_select)
      description: "Volba: Časovač (podle timeru) / until_next_schedule (do další změny rozvrhu)."
      selector:
        entity:
          domain: input_select


mode: restart
initial_state: true

# ---------------------------------------------------------------
# TRIGGER
# ---------------------------------------------------------------
trigger:
  # Změna stavu Scheduler Booleanu (Komfort <-> Eco)
  - platform: state
    entity_id: !input scheduler_entity

  # Změna enable flagu nebo režimu
  - platform: state
    entity_id:
      - !input schedule_enable
      - input_select.topny_rezim

  # Změna „poslední komfortní teploty“ → reapply, pokud jsme v okně
  - platform: state
    entity_id: !input last_comfort_helper

  # Ruční změna setpointu na hlavici → zachyť komfort + případně reaguj
  - platform: state
    entity_id: !input climate_entity
    attribute: temperature

  # Změna ECO teploty
  - platform: state
    entity_id: !input eco_temp_default

  # -----------------------------------------------------------------
  # 🧠 MANUÁLNÍ OVERRIDE – nové triggery
  # -----------------------------------------------------------------
  - platform: state
    entity_id: !input manual_override_boolean

  - platform: state
    entity_id: !input manual_override_timer

  - platform: state
    entity_id: !input manual_override_type

# ---------------------------------------------------------------
# CONDITIONS
# ---------------------------------------------------------------
condition:
  - condition: state
    entity_id: !input schedule_enable
    state: "on"

# ---------------------------------------------------------------
# VARIABLES
# ---------------------------------------------------------------
variables:
  zone_name: !input zone_name
  climate_entity: !input climate_entity
  scheduler_entity_id: !input scheduler_entity
  last_comfort_helper: !input last_comfort_helper
  eco_temp_entity: !input eco_temp_default
  boost_active_entity: !input boost_active
  cooldown_seconds: !input cooldown_seconds

  manual_override_boolean: !input manual_override_boolean
  manual_override_timer: !input manual_override_timer
  manual_override_type: !input manual_override_type

  mode: "{{ states('input_select.topny_rezim') }}"
  eco_temp: "{{ states(eco_temp_entity) | float(15) }}"
  last_comfort: "{{ states(last_comfort_helper) | float(22) }}"
  new_set: "{{ state_attr(climate_entity, 'temperature') | float(0) }}"

  # Co spustilo automatizaci
  is_scheduler_trigger: "{{ trigger.platform == 'state' and trigger.entity_id == scheduler_entity_id }}"
  is_climate_trigger: "{{ trigger.platform == 'state' and trigger.entity_id == climate_entity }}"

  # Antispam
  now_ts: "{{ as_timestamp(now()) }}"
  last_trig_ts: >
    {{ as_timestamp(state_attr(this.entity_id, 'last_triggered'))
       if state_attr(this.entity_id, 'last_triggered') else 0 }}
  since_last: "{{ (now_ts - last_trig_ts) | float(999999) }}"

  # === OKNO ===
  in_window: "{{ is_state(scheduler_entity_id, 'on') }}"

  # -----------------------------------------------------------------
  # 🧠 MANUÁLNÍ OVERRIDE – stav
  # -----------------------------------------------------------------
  override_active: "{{ is_state(manual_override_boolean, 'on') }}"
  override_timer_active: "{{ is_state(manual_override_timer, 'active') }}"
  override_type: "{{ states(manual_override_type) }}"

  # -----------------------------------------------------------------
  # 🧠 Ruční zásah uživatele (UI / fyzická hlavice)
  # - user_id != null (změna z Dashboardu/Appky)
  # - parent_id == null (změna fyzicky na zařízení, která nemá "rodiče" v automatizaci)
  # - from_state != null (pojistka proti „restore/startup“ událostem)
  # -----------------------------------------------------------------
  is_user_action: >
    {{ trigger is defined
      and trigger.to_state is defined
      and trigger.to_state.context is defined
      and (
        (trigger.to_state.context.user_id is not none)
        or (
          trigger.to_state.context.user_id is none
          and trigger.to_state.context.parent_id is none
          and trigger.from_state is not none
        )
      ) }}

  override_should_apply: >
    {{ override_active
       and (override_type == 'until_next_schedule'
            or (override_type == 'Časovač' and override_timer_active)) }}

# ---------------------------------------------------------------
# ACTION
# ---------------------------------------------------------------
action:
  # ===============================================================
  # 0) 🧠 MANUÁLNÍ OVERRIDE – ukončení „do další změny rozvrhu“
  # ===============================================================
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ override_active and override_type == 'until_next_schedule' and is_scheduler_trigger }}"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: "{{ manual_override_boolean }}"
          - service: timer.cancel
            target:
              entity_id: "{{ manual_override_timer }}"
          - service: logbook.log
            data:
              name: "{{ zone_name }}"
              message: "Manuální override ukončen (další změna rozvrhu)."
              entity_id: "{{ climate_entity }}"

  # ===============================================================
  # 0b) 🧠 MANUÁLNÍ OVERRIDE – priorita nad rozvrhem
  #     (každá hlavice se nastaví na last_comfort)
  # ===============================================================
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ override_should_apply and mode in ['Auto','Boost','Eco'] }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ climate_entity }}"
            data:
              hvac_mode: heat

          - condition: template
            value_template: >
              {{ ((state_attr(climate_entity, 'temperature') | float)
                  - (last_comfort | float)) | abs > 0.1 }}

          - service: climate.set_temperature
            target:
              entity_id: "{{ climate_entity }}"
            data:
              temperature: "{{ last_comfort }}"

          - service: logbook.log
            data:
              name: "{{ zone_name }}"
              message: "MANUAL override – nastaven last comfort {{ last_comfort }} °C"
              entity_id: "{{ climate_entity }}"

          - stop: "MANUAL override má prioritu – rozvrh se neaplikuje"

  # ---------------------------------------------------------------
  # 1) ZACHYCENÍ KOMFORTNÍ TEPLOTY PŘI RUČNÍ ZMĚNĚ SETPOINTU
  # ---------------------------------------------------------------
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_climate_trigger }}"
          - condition: template
            value_template: "{{ new_set >= (eco_temp + 0.2) }}"
          - condition: template
            value_template: "{{ (last_comfort - new_set) | abs > 0.1 }}"
          - condition: template
            value_template: "{{ states(boost_active_entity) == 'off' }}"
        sequence:
          - service: input_number.set_value
            target:
              entity_id: !input last_comfort_helper
            data:
              value: "{{ new_set }}"

          - service: logbook.log
            data:
              name: "{{ zone_name }}"
              message: "Uložena komfortní teplota: {{ new_set }} °C"
              entity_id: "{{ climate_entity }}"

  # 1b) Ruční změna v okně: uloženo, hned nepřepisuj zpět
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ is_climate_trigger
                 and mode in ['Auto','Boost']
                 and in_window
                 and new_set >= (eco_temp + 0.2) }}
        sequence:
          - stop: "Ruční komfort v okně: uloženo, rozvrh teď nepřepisuje"

  # ===============================================================
  # 1c) 🧠 Volitelné chování: Ruční změna mimo okno → aktivuj override
  #     (pokud chceš, aby otočení hlavice mimo okno „zapnulo manuál“)
  # ===============================================================
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ is_climate_trigger
                 and is_user_action
                 and mode in ['Auto','Boost']
                 and (not in_window)
                 and (not override_active)
                 and new_set >= (eco_temp + 0.2) }}
        sequence:
          - service: input_select.select_option
            target:
              entity_id: "{{ manual_override_type }}"
            data:
              option: "until_next_schedule"

          - service: timer.cancel
            target:
              entity_id: "{{ manual_override_timer }}"

          - service: input_boolean.turn_on
            target:
              entity_id: "{{ manual_override_boolean }}"

          # timed = čekáme, že timer si spustíš z UI (nebo doplníme později)
          # until_next_schedule = timer se ignoruje
          - service: logbook.log
            data:
              name: "{{ zone_name }}"
              message: "Ruční zásah mimo okno – aktivován manuální override (until_next_schedule)."
              entity_id: "{{ climate_entity }}"

          - stop: "Ruční zásah mimo okno – přepnuto do manuálního override"

  # ---------------------------------------------------------------
  # 0) ANTISPAM – aplikaci rozvrhu throttle (NEPLATÍ pro scheduler trigger a neplatí pro ruční otočení)
  # ---------------------------------------------------------------
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ (cooldown_seconds | int(0)) > 0
                 and not is_scheduler_trigger
                 and not is_climate_trigger
                 and (since_last | float(999999)) < (cooldown_seconds | int(0)) }}
        sequence:
          - stop: "Antispam: cooldown aktivní"

  # ---------------------------------------------------------------
  # 2) APLIKACE REŽIMŮ (Eco / Auto+Boost / Off)
  # ---------------------------------------------------------------
  - choose:
      # ECO
      - conditions:
          - condition: template
            value_template: "{{ mode == 'Eco' }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ climate_entity }}"
            data:
              hvac_mode: heat

          - condition: template
            value_template: >
              {{ ((state_attr(climate_entity, 'temperature') | float)
                  - (eco_temp | float)) | abs > 0.1 }}

          - service: climate.set_temperature
            target:
              entity_id: "{{ climate_entity }}"
            data:
              temperature: "{{ eco_temp }}"

          - service: logbook.log
            data:
              name: "{{ zone_name }}"
              message: "Globální ECO režim – cílová teplota {{ eco_temp }} °C"
              entity_id: "{{ climate_entity }}"

      # Auto / Boost
      - conditions:
          - condition: template
            value_template: "{{ mode in ['Auto', 'Boost'] }}"
        sequence:
          - choose:
              # V OKNĚ → poslední komfort
              - conditions:
                  - condition: template
                    value_template: "{{ in_window }}"
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: "{{ climate_entity }}"
                    data:
                      hvac_mode: heat

                  - condition: template
                    value_template: >
                      {{ ((state_attr(climate_entity, 'temperature') | float)
                          - (last_comfort | float)) | abs > 0.1 }}

                  - service: climate.set_temperature
                    target:
                      entity_id: "{{ climate_entity }}"
                    data:
                      temperature: "{{ last_comfort }}"

                  - service: logbook.log
                    data:
                      name: "{{ zone_name }}"
                      message: "Komfortní režim {{ last_comfort }} °C (inteligentní spuštění)"
                      entity_id: "{{ climate_entity }}"

              # MIMO OKNO → ECO
              - conditions:
                  - condition: template
                    value_template: "{{ not in_window }}"
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: "{{ climate_entity }}"
                    data:
                      hvac_mode: heat

                  - condition: template
                    value_template: >
                      {{ ((state_attr(climate_entity, 'temperature') | float)
                          - (eco_temp | float)) | abs > 0.1 }}

                  - service: climate.set_temperature
                    target:
                      entity_id: "{{ climate_entity }}"
                    data:
                      temperature: "{{ eco_temp }}"

                  - service: logbook.log
                    data:
                      name: "{{ zone_name }}"
                      message: "ECO {{ eco_temp }} °C (inteligentní spuštění)"
                      entity_id: "{{ climate_entity }}"

      # Off
      - conditions:
          - condition: template
            value_template: "{{ mode == 'Off' }}"
        sequence:
          - service: logbook.log
            data:
              name: "{{ zone_name }}"
              message: "Režim Off – rozvrh nemění cílovou teplotu."
              entity_id: "{{ climate_entity }}"
