# YAML 2024.10
# =====================================================================
# 🧠 SOUBOR: /config/heating/schedule/automation/start_end/start_end_prizemi_michal.yaml
# =====================================================================
# AUTOMATIZACE – události start/end pro jednotlivé zóny
# ---------------------------------------------------------------------
automation:
  # ==============================================================================================================================================================================
  # PŘÍZEMÍ – MICHAL
  # ==============================================================================================================================================================================

  - id: sched_prizemi_michal_start
    alias: "Rozvrh: Přízemí Michal – START komfortního okna"
    mode: restart
    triggers:
      - trigger: template
        value_template: "{{ now().strftime('%H:%M') == start_time[:5] }}" # start Po,út,st,čt,pá,so,ne
    condition:
      - condition: state
        entity_id: input_boolean.schedule_enable_prizemi_michal
        state: "on" # rozvrh aktivní
      - condition: template
        value_template: "{{ states('input_select.topny_rezim') != 'Off' }}" # Off = nic nedělej
    actions:
      - action: script.schedule_set_zone_comfort
        data:
          climate_entity: climate.prizemi_michal # cílová hlavice
          last_user_temp_sensor: sensor.last_user_temp_prizemi_michal

  - id: sched_prizemi_michal_end
    alias: "Rozvrh: Přízemí Michal – KONEC komfortního okna → útlum"
    mode: restart
    triggers:
      - trigger: template
        value_template: "{{ now().strftime('%H:%M') == end_time[:5] }}" # end Po,út,st,čt,pá,so,ne
    condition:
      - condition: state
        entity_id: input_boolean.schedule_enable_prizemi_michal
        state: "on"
      - condition: template
        value_template: "{{ states('binary_sensor.kotel_boost_active') == 'off' }}" # Boost má přednost
    actions:
      - action: script.schedule_set_zone_setback
        data:
          climate_entity: climate.prizemi_michal