# =====================================================================
# Soubor   : config/heating/control/External senzors/zone_1p_kuchyn_external_sensor.yaml
# Modul    : Externí senzor – 1. patro Jídelna
# Účel     : Přeposílání teploty z externího senzoru do hlavice Danfoss
# Autor    : Michal
# Poslední úprava : 2025-11-19
# Poznámka : YAML syntaxe podle HA 2024.10 (triggers / conditions / actions)
# =====================================================================

automation:
  # ===================================================================
  # SEKCE: Automatizace – externí senzor 1P Jídelna
  # ===================================================================

  # -------------------------------------------------------------------
  # AUTOMATIZACE: Přeposlat teplotu z externího senzoru do hlavice
  # Logika:
  # - spouští se při změně teploty, po startu HA a každých 10 minut
  # - načte hodnotu senzoru, zkonvertuje na číslo a ověří rozsah
  # - pokud je hodnota platná (-40 až +60 °C), uloží ji do hlavice Danfoss
  # -------------------------------------------------------------------
  - alias: "Danfoss 1P Jídelna – přeposlat teplotu z externího senzoru"
    id: danfoss_1p_jidelna_external_temp_forward
    description: >
      Přeposílá teplotu z externího Zigbee senzoru tz3000_jidelna do
      hlavice Danfoss v kuchyni. Zajišťuje obnovu po restartu a pravidelný refresh.
    mode: queued

    triggers:
      # Spouštěč 1: změna hodnoty externího senzoru
      - trigger: state
        entity_id: sensor.tz3000_jidelna_teplota

      # Spouštěč 2: po restartu HA
      - trigger: homeassistant
        event: start

      # Spouštěč 3: pojistný refresh každých 10 minut
      - trigger: time_pattern
        minutes: "/10"

    conditions: []

    actions:
      # ---------------------------------------------------------------
      # 1) PŘÍPRAVA PROMĚNNÝCH
      # ---------------------------------------------------------------
      - variables:
          raw: "{{ states('sensor.tz3000_jidelna_teplota') }}"
          temp: "{{ raw | float(none) }}"

      # ---------------------------------------------------------------
      # 2) Ověření hodnoty + přenos do hlavice
      # - hodnota musí být definovaná
      # - musí být v reálném rozsahu (-40 až +60 °C)
      # + podmínka, že rozdíl je > 0.1 °C
      # ---------------------------------------------------------------
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{ temp is not none and -40 < temp < 60 }}
              - condition: template
                value_template: >
                  {{ (states('number.1p_jidelna_senzor_externi_teploty') | float(0) - temp) | abs > 0.1 }}
            sequence:
              - action: number.set_value
                target:
                  entity_id: number.1p_jidelna_senzor_externi_teploty
                data:
                  value: "{{ temp }}"
