# =====================================================================
# Soubor   : config/heating/control/External senzors/zone_sklep_michal_external_sensor.yaml
# Modul    : Externí senzor – sklep Michal
# Účel     : Přeposílání teploty z externího senzoru do hlavice Danfoss
# Autor    : Michal
# Poslední úprava : 2025-11-19
# Poznámka : YAML syntaxe podle HA 2024.10 (triggers / conditions / actions)
# =====================================================================

automation:
  # ===================================================================
  # SEKCE: Automatizace – externí senzor sklep Michal
  # ===================================================================

  # -------------------------------------------------------------------
  # AUTOMATIZACE: Přeposlat teplotu z externího senzoru do hlavice
  # Logika:
  # - spouští se při změně teploty, po startu HA a každých 10 minut
  # - načte hodnotu senzoru, převede ji na číslo a ověří rozsah
  # - pokud je hodnota platná (-40 až +60 °C), uloží ji do hlavice Danfoss
  # -------------------------------------------------------------------
  - alias: "Danfoss sklep Michal – přeposlat teplotu z externího senzoru"
    id: danfoss_sklep_michal_external_temp_forward
    description: >
      Přeposílá teplotu z externího senzoru mi_air_purifier_2h do hlavice
      Danfoss ve sklepě. Zajišťuje obnovu po restartu HA a pravidelný refresh.
    mode: queued

    triggers:
      # Spouštěč 1: změna hodnoty externího senzoru
      - trigger: state
        entity_id: sensor.mi_air_purifier_2h_teplota

      # Spouštěč 2: po restartu HA
      - trigger: homeassistant
        event: start

      # Spouštěč 3: pojistný refresh každých 10 minut
      - trigger: time_pattern
        minutes: "/10"

    conditions: []

    actions:
      # ---------------------------------------------------------------
      # 1) PŘÍPRAVA PROMĚNNÝCH
      # - raw  = textová hodnota senzoru (např. "21.7")
      # - temp = číselná hodnota teploty (float) nebo None při chybě
      # ---------------------------------------------------------------
      - variables:
          raw: "{{ states('sensor.mi_air_purifier_2h_teplota') }}"
          temp: "{{ raw | float(none) }}"

      # ---------------------------------------------------------------
      # 2) Ověření hodnoty + přenos do hlavice
      # - hodnota musí být definovaná
      # - musí být v reálném rozsahu (-40 až +60 °C)
      # ---------------------------------------------------------------
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{ temp is not none and -40 < temp < 60 }}
            sequence:
              - action: number.set_value
                target:
                  entity_id: number.sklep_michal_senzor_externi_teploty
                data:
                  value: "{{ temp }}"
        default: []
