# =====================================================================
# 🧲 2. patro – Máma: zachytávání poslední KOMFORTNÍ teploty
# - Sleduje změny setpointu (attribute: temperature) na hlavici (máma).
# - Pokud nová teplota > ECO (s malou hysterezí), uloží ji do 2p_mama_last_comfort.
# - Díky tomu se po skončení ECO vždy vrátí opravdu poslední „komfort“.
# =====================================================================

automation:
  - alias: "Zachytni poslední komfort – 2. patro Máma"
    id: capture_last_comfort_2p_mama
    mode: restart
    initial_state: true

    # 🔔 Spouštěč: změna žádané teploty na hlavici (máma)
    trigger:
      - platform: state
        entity_id: climate.danfoss_etrv0103_2
        attribute: temperature

    # 📦 Proměnné pro přehlednost
    variables:
      new_set: "{{ state_attr('climate.danfoss_etrv0103_2', 'temperature') | float(0) }}"
      eco: "{{ states('input_number.eco_temp_default') | float(18) }}"

    # ✅ Ukládáme jen KOMFORT (tj. > ECO + 0.2 °C hystereze)
    condition:
      - condition: template
        value_template: "{{ new_set >= (eco + 0.2) }}"

    # 💾 Zapiš poslední komfortní teplotu do helperu
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.2p_mama_last_comfort
        data:
          value: "{{ new_set }}"