# YAML 2024.10
# =====================================================================
# 🧠 SOUBOR: /config/heating/control/kotel_control.yaml
# =====================================================================
# 📌 CÍL:
# Tento modul zajišťuje automatické řízení kotle (Aqara T2) podle
# poptávky zón, režimu topení a konfigurovaných prahů.
#
# 💡 Logika:
#   - „Zapni kotel“ → když jsou splněny všechny prahy (AND)
#   - „Vypni kotel“ → když prahy přestanou platit nebo je aktivní blokace
#   - Zahrnuje anti-cycling zpoždění (ON/OFF delay)
#
# 🧩 Vstupy:
#   - input_boolean.topny_system_enable
#   - input_select.topny_rezim
#   - binary_sensor.kotel_threshold_any_ok
#   - binary_sensor.kotel_mode_off_block
#   - sensor.kotel_effective_on_delay_sec / off_delay_sec
#   - sensor.kotel_aktivni_zony_pocet / kotel_poptavka_prumer
#
# ⚡ Výstup:
#   - switch.kotel_rele_spinac (Aqara T2 relé)
# =====================================================================

automation:
  # ---------------------------------------------------------------
  # ▶️ ZAPNOUT KOTEL
  # ---------------------------------------------------------------
  - id: kotel_turn_on_by_policy
    alias: "Kotel: zapnout při splnění politiky"
    description: "Zapne relé kotle po zpoždění, pokud platí prahy a není blokace."
    mode: restart

    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.kotel_threshold_any_ok
          - binary_sensor.kotel_mode_off_block
          - input_boolean.topny_system_enable
          - input_select.topny_rezim
          - input_boolean.boost_now
          - input_datetime.boost_until
          - input_number.kotel_on_delay_sec
          - sensor.kotel_aktivni_zony_pocet
          - sensor.kotel_poptavka_prumer
          - sensor.kotel_poptavka_max

    condition:
      - condition: state
        entity_id: input_boolean.topny_system_enable
        state: "on"
      - condition: state
        entity_id: binary_sensor.kotel_mode_off_block
        state: "off"
      - condition: state
        entity_id: binary_sensor.kotel_threshold_any_ok
        state: "on"

    actions:
      - delay:
          seconds: "{{ states('sensor.kotel_effective_on_delay_sec') | int(0) }}"
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.topny_system_enable
                state: "on"
              - condition: state
                entity_id: binary_sensor.kotel_mode_off_block
                state: "off"
              - condition: state
                entity_id: binary_sensor.kotel_threshold_any_ok
                state: "on"
            sequence:
              - action: switch.turn_on
                target:
                  entity_id: switch.kotel_rele_spinac

  # ---------------------------------------------------------------
  # ⏹ VYPNOUT KOTEL
  # ---------------------------------------------------------------
  - id: kotel_turn_off_by_policy
    alias: "Kotel: vypnout při nesplnění politiky / blokaci"
    description: "Vypne relé kotle po zpoždění, když prahy neplatí, režim je Off, nebo master OFF."
    mode: restart

    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.kotel_threshold_any_ok
          - binary_sensor.kotel_mode_off_block
          - input_boolean.topny_system_enable
          - input_select.topny_rezim
          - input_boolean.boost_now
          - input_datetime.boost_until
          - input_number.kotel_off_delay_sec
          - sensor.kotel_aktivni_zony_pocet
          - sensor.kotel_poptavka_prumer
          - sensor.kotel_poptavka_max

    condition: []

    action:
      - choose:
          # ⛔ Master OFF
          - conditions:
              - condition: state
                entity_id: input_boolean.topny_system_enable
                state: "off"
            sequence:
              - delay:
                  seconds: "{{ states('sensor.kotel_effective_off_delay_sec') | int(0) }}"
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: input_boolean.topny_system_enable
                        state: "off"
                    sequence:
                      - action: switch.turn_off
                        target:
                          entity_id: switch.kotel_rele_spinac

          # ⛔ Režim Off
          - conditions:
              - condition: state
                entity_id: binary_sensor.kotel_mode_off_block
                state: "on"
            sequence:
              - delay:
                  seconds: "{{ states('sensor.kotel_effective_off_delay_sec') | int(0) }}"
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: binary_sensor.kotel_mode_off_block
                        state: "on"
                    sequence:
                      - action: switch.turn_off
                        target:
                          entity_id: switch.kotel_rele_spinac

          # ⛔ Nesplněné prahy
          - conditions:
              - condition: state
                entity_id: binary_sensor.kotel_threshold_any_ok
                state: "off"
            sequence:
              - delay:
                  seconds: "{{ states('sensor.kotel_effective_off_delay_sec') | int(0) }}"
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: binary_sensor.kotel_threshold_any_ok
                        state: "off"
                    sequence:
                      - action: switch.turn_off
                        target:
                          entity_id: switch.kotel_rele_spinac
