# =====================================================================
# 🔌 KOTEL – PRAHY + ŘÍZENÍ RELÉ (Aqara T2)
# - Zapnout: master ON ∧ režim ≠ Off ∧ (min. aktivních zón) ∧ (min. průměrná poptávka)
# - Vypnout: master OFF ∨ režim Off ∨ (práhy nesplněny)
# - Anti-cycling: on/off delay + re-check po zpoždění
# =====================================================================

# -----------------------------
# ✅ PRAHOVÉ BINÁRNÍ SENZORY
# -----------------------------
template:
  - binary_sensor:

      # Splněno: minimální počet aktivních zón
      - name: "kotel_threshold_min_active_zones_ok"
        unique_id: kotel_threshold_min_active_zones_ok
        state: >
          {% set aktivni = states('sensor.kotel_aktivni_zony_pocet') | int(0) %}
          {% set min_zony = states('input_number.kotel_min_active_zones') | int(1) %}
          {{ aktivni >= min_zony }}
        device_class: connectivity

      # Splněno: minimální průměrná poptávka aktivních zón (%)
      - name: "kotel_threshold_min_avg_demand_ok"
        unique_id: kotel_threshold_min_avg_demand_ok
        state: >
          {% set avg = states('sensor.kotel_poptavka_prumer') | float(0) %}
          {% set min_avg = states('input_number.kotel_min_avg_demand_pct') | float(15) %}
          {{ avg >= min_avg }}
        device_class: connectivity

      # 🔁 HLAVNÍ PRÁH – VŠECHNY PODMÍNKY MUSÍ PLATIT (AND)
      # (dříve to bylo OR → způsobovalo zbytečné sepnutí při malé poptávce)
      - name: "kotel_threshold_any_ok"
        unique_id: kotel_threshold_all_ok   # ID může zůstat jiné; entity_id zůstane podle name
        icon: mdi:checkbox-marked-circle
        state: >
          {{ is_state('binary_sensor.kotel_threshold_min_active_zones_ok','on')
             and is_state('binary_sensor.kotel_threshold_min_avg_demand_ok','on') }}

# -----------------------------
# ⚙️ AUTOMATIZACE (BEZE ZMĚNY)
# -----------------------------
automation:

  # ---------------------------------------------------------------
  # ▶️ ZAPNOUT KOTEL
  # ---------------------------------------------------------------
  - id: kotel_turn_on_by_policy
    alias: "Kotel: zapnout při splnění politiky"
    description: "Zapne relé kotle po zpoždění, pokud platí prahy a není blokace."
    mode: restart  # nová změna zruší předchozí běh (aby se delay nepřekrýval)

    trigger:
      - platform: state
        entity_id:
          - binary_sensor.kotel_threshold_any_ok
          - binary_sensor.kotel_mode_off_block
          - input_boolean.topny_system_enable
          - input_select.topny_rezim
          - input_boolean.boost_now
          - input_datetime.boost_until
          - input_number.kotel_on_delay_sec
          - sensor.kotel_aktivni_zony_pocet
          - sensor.kotel_poptavka_prumer
          - sensor.kotel_poptavka_max

    # Zapneme, když:
    # - master je ON
    # - režim není Off (tj. kotel_mode_off_block == off)
    # - a (min. aktivní zóny) ∧ (min. průměrná poptávka)
    condition:
      - condition: state
        entity_id: input_boolean.topny_system_enable
        state: "on"
      - condition: state
        entity_id: binary_sensor.kotel_mode_off_block
        state: "off"
      - condition: state
        entity_id: binary_sensor.kotel_threshold_any_ok
        state: "on"

    action:
      # ⏳ Anti-cycling zpoždění (konfigurovatelné)
      - delay:
          seconds: "{{ states('input_number.kotel_on_delay_sec') | int(0) }}"

      # ✅ Re-check po zpoždění
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.topny_system_enable
                state: "on"
              - condition: state
                entity_id: binary_sensor.kotel_mode_off_block
                state: "off"
              - condition: state
                entity_id: binary_sensor.kotel_threshold_any_ok
                state: "on"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.aqara_lumi_switch_acn047_spinac

  # ---------------------------------------------------------------
  # ⏹ VYPNOUT KOTEL
  # ---------------------------------------------------------------
  - id: kotel_turn_off_by_policy
    alias: "Kotel: vypnout při nesplnění politiky / blokaci"
    description: "Vypne relé kotle po zpoždění, když prahy neplatí, režim je Off, nebo master OFF."
    mode: restart

    trigger:
      - platform: state
        entity_id:
          - binary_sensor.kotel_threshold_any_ok
          - binary_sensor.kotel_mode_off_block
          - input_boolean.topny_system_enable
          - input_select.topny_rezim
          - input_boolean.boost_now
          - input_datetime.boost_until
          - input_number.kotel_off_delay_sec
          - sensor.kotel_aktivni_zony_pocet
          - sensor.kotel_poptavka_prumer
          - sensor.kotel_poptavka_max

    condition: []

    action:
      - choose:
          # ⛔ Master OFF
          - conditions:
              - condition: state
                entity_id: input_boolean.topny_system_enable
                state: "off"
            sequence:
              - delay:
                  seconds: "{{ states('input_number.kotel_off_delay_sec') | int(0) }}"
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: input_boolean.topny_system_enable
                        state: "off"
                    sequence:
                      - service: switch.turn_off
                        target:
                          entity_id: switch.aqara_lumi_switch_acn047_spinac

          # ⛔ Režim Off
          - conditions:
              - condition: state
                entity_id: binary_sensor.kotel_mode_off_block
                state: "on"
            sequence:
              - delay:
                  seconds: "{{ states('input_number.kotel_off_delay_sec') | int(0) }}"
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: binary_sensor.kotel_mode_off_block
                        state: "on"
                    sequence:
                      - service: switch.turn_off
                        target:
                          entity_id: switch.aqara_lumi_switch_acn047_spinac

          # ⛔ Nesplněné prahy
          - conditions:
              - condition: state
                entity_id: binary_sensor.kotel_threshold_any_ok
                state: "off"
            sequence:
              - delay:
                  seconds: "{{ states('input_number.kotel_off_delay_sec') | int(0) }}"
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: binary_sensor.kotel_threshold_any_ok
                        state: "off"
                    sequence:
                      - service: switch.turn_off
                        target:
                          entity_id: switch.aqara_lumi_switch_acn047_spinac
