# =====================================================================
# 🧠 SOUBOR: /config/heating/control/mode_logic.yaml
# =====================================================================
# 🎛️ LOGIKA REŽIMŮ TOPENÍ (Auto / Eco / Boost / Off)
# ---------------------------------------------------------------------
# 📌 CÍL:
# Tento modul zajišťuje základní logiku přepínání režimů topení.
# Reaguje na změnu `input_select.topny_rezim` a podle toho:
#   🔹 Při „Off“ okamžitě vypne kotel (relé Aqara T2)
#   🔹 U ostatních režimů pouze zaznamená změnu do Logbooku
#
# ⚙️ FUNKCE:
# - Sleduje změny režimu (Auto / Eco / Boost / Off)
# - U režimu Off zajistí okamžité vypnutí kotle
# - Pro všechny režimy zapisuje přehledné události do Logbooku
#
# 🚫 Co tento soubor NEDĚLÁ:
# - Neřídí žádné binary sensory (blokace je v `mode_engine.yaml`)
# - Nepočítá účinné prahy (`effective_*` – řeší `mode_engine.yaml`)
# - Neřeší Boost logiku / časování (`boost_now`, `boost_until`)
#
# 🔗 NAPOJENÍ:
# - `mode_engine.yaml` → vypočítává prahy a blokace
# - `kotel_control.yaml` → používá tyto prahy pro spínání kotle
#
# 📘 STANDARD:
# - Všechny reakce čistě na úrovni přepínače režimu
# - Logbook používán pro auditní a diagnostické účely
# =====================================================================

automation:
  - alias: "Topení – logika režimů (čistá)"
    id: heating_mode_logic_clean
    description: "Reaguje na změnu režimu. Pro Off vypne kotel; ostatní režimy pouze loguje."
    mode: restart # Restart = vždy reaguje na poslední změnu

    # 🛎️ Spouštěč: změna režimu topení
    triggers:
      - trigger: state
        entity_id: input_select.topny_rezim

    action:
      - choose:
          # 🔻 REŽIM OFF → okamžité vypnutí kotle
          - conditions:
              - condition: state
                entity_id: input_select.topny_rezim
                state: "Off"
            sequence:
              - action: switch.turn_off # Vypni relé kotle
                target:
                  entity_id: switch.kotel_rele
              - action: logbook.log # Zaznamenej událost
                data:
                  name: "Topení – režimy"
                  message: "Režim přepnut na Off → kotel vypnut."
                  entity_id: switch.kotel_rele

          # 🔸 REŽIM AUTO → standardní provoz
          - conditions:
              - condition: state
                entity_id: input_select.topny_rezim
                state: "Auto"
            sequence:
              - action: logbook.log
                data:
                  name: "Topení – režimy"
                  message: "Režim Auto → používají se účinné prahy z mode_engine."
                  entity_id: input_select.topny_rezim

          # 🌿 REŽIM ECO → úspornější režim
          - conditions:
              - condition: state
                entity_id: input_select.topny_rezim
                state: "Eco"
            sequence:
              - action: logbook.log
                data:
                  name: "Topení – režimy"
                  message: "Režim Eco → přísnější účinné prahy (mode_engine)."
                  entity_id: input_select.topny_rezim

          # ⚡ REŽIM BOOST → krátkodobé „přitop“
          - conditions:
              - condition: state
                entity_id: input_select.topny_rezim
                state: "Boost"
            sequence:
              - action: logbook.log
                data:
                  name: "Topení – režimy"
                  message: "Režim Boost → uvolněné účinné prahy + časování (mode_engine)."
                  entity_id: input_select.topny_rezim
