# YAML 2024.10
# =====================================================================
# 🧠 SOUBOR: /config/heating/control/mode_logic.yaml
# =====================================================================

automation:
  - alias: "Topení – logika režimů (čistá)"
    id: heating_mode_logic_clean
    description: "Reaguje na změnu režimu. Pro Off vypne kotel; ostatní režimy pouze loguje."
    mode: restart

    triggers:
      - trigger: state
        entity_id: input_select.topny_rezim

    conditions:
      - condition: template
        value_template: "{{ trigger.from_state is not none and trigger.from_state.state != trigger.to_state.state }}"

    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.topny_rezim
                state: "Off"
            sequence:
              - action: switch.turn_off
                target:
                  entity_id: switch.kotel_rele_spinac
              - action: logbook.log
                data:
                  name: "Topení – režimy"
                  message: "Režim přepnut na Off → kotel vypnut."
                  entity_id: switch.kotel_rele_spinac

          - conditions:
              - condition: state
                entity_id: input_select.topny_rezim
                state: "Auto"
            sequence:
              - action: logbook.log
                data:
                  name: "Topení – režimy"
                  message: "Režim Auto → používají se účinné prahy (policy/mode_engine)."
                  entity_id: input_select.topny_rezim

          - conditions:
              - condition: state
                entity_id: input_select.topny_rezim
                state: "Eco"
            sequence:
              - action: logbook.log
                data:
                  name: "Topení – režimy"
                  message: "Režim Eco → přísnější účinné prahy (policy/mode_engine)."
                  entity_id: input_select.topny_rezim

          - conditions:
              - condition: state
                entity_id: input_select.topny_rezim
                state: "Boost"
            sequence:
              - action: logbook.log
                data:
                  name: "Topení – režimy"
                  message: "Režim Boost → uvolněné prahy + časování (mode_engine)."
                  entity_id: input_select.topny_rezim
