# ==============================================================================
# MODE_ENGINE.YAML – GLOBÁLNÍ ŘÍZENÍ REŽIMŮ TOPENÍ
# ==============================================================================
# CÍL:
# Tento modul řídí **globální režimy topení** a určuje účinné prahy,
# které používá logika kotle (`kotel_control.yaml`). Zajišťuje dynamickou
# úpravu chování systému podle režimu (Auto / Eco / Boost / Off) a
# aktivaci Boostu na omezený čas.
# ==============================================================================

template:

  # ── BOOST aktivní? ──────────────────────────────────────────────────────────
  - binary_sensor:
      - name: "kotel_boost_active"                                    # Stav: Boost zapnutý
        unique_id: kotel_boost_active
        state: >
          {% set mode  = states('input_select.topny_rezim') %}        # Aktuální režim
          {% set bn    = is_state('input_boolean.boost_now','on') %}  # Tlačítko Boost
          {% set until = states('input_datetime.boost_until') %}      # Čas do kdy platí
          {% set nowts = now().timestamp() %}
          {% set uts   = as_timestamp(until, default=0) %}
          {{ mode == 'Boost' or bn or (nowts < uts) }}                # Aktivní, pokud aspoň jedna podmínka


  # ── Blokace kotle (Off / master OFF) ────────────────────────────────────────
  - binary_sensor:
      - name: "kotel_mode_off_block"                                    # True = nesmí se spínat
        unique_id: kotel_mode_off_block
        state: >
          {{ is_state('input_select.topny_rezim','Off')
             or is_state('input_boolean.topny_system_enable','off') }}  # Master vypnut


  # ── ÚČINNÉ PRAHY dle režimu ─────────────────────────────────────────
  - sensor:
      - name: "kotel_effective_min_active_zones"
        unique_id: kotel_effective_min_active_zones
        state: >
          {% set mode = states('input_select.topny_rezim') %}
          {% set base = states('input_number.kotel_min_active_zones') | int(0) %}
          {% if mode == 'Eco' %}                                                  # Přísnější v Eco
            {{ [1, base + 1] | max }}
          {% elif mode == 'Boost' %}                                              # Uvolněné v Boost
            1
          {% else %}  {# Auto i Off #}
            {{ base }}
          {% endif %}

      - name: "kotel_effective_min_avg_demand_pct"
        unique_id: kotel_effective_min_avg_demand_pct
        unit_of_measurement: "%"
        state: >
          {% set mode = states('input_select.topny_rezim') %}
          {% set base = states('input_number.kotel_min_avg_demand_pct') | int(0) %}
          {% if mode == 'Eco' %}                                                    # +10 % v Eco
            {{ [0, base + 10] | max }}
          {% elif mode == 'Boost' %}                                                # 0 % v Boost
            0
          {% else %}
            {{ base }}
          {% endif %}

      - name: "kotel_effective_on_delay_sec"
        unique_id: kotel_effective_on_delay_sec
        unit_of_measurement: "s"
        state: >
          {% set mode = states('input_select.topny_rezim') %}
          {% set base = states('input_number.kotel_on_delay_sec') | int(0) %}
          {% if mode == 'Eco' %}                                                    # +30 s v Eco
            {{ base + 30 }}
          {% elif mode == 'Boost' %}                                                # 0 s v Boost
            0
          {% else %}
            {{ base }}
          {% endif %}

      - name: "kotel_effective_off_delay_sec"
        unique_id: kotel_effective_off_delay_sec
        unit_of_measurement: "s"
        state: >
          {% set mode = states('input_select.topny_rezim') %}
          {% set base = states('input_number.kotel_off_delay_sec') | int(0) %}
          {% if mode == 'Eco' %}                                                    # +60 s v Eco
            {{ base + 60 }}
          {% elif mode == 'Boost' %}                                                # min 300 s doběh v Boost
            {{ [base, 300] | max }}
          {% else %}
            {{ base }}
          {% endif %}

# =====================================================================
# 🤖 AUTOMATIZACE PRO BOOST
# =====================================================================
automation:
  # ▶️ Start Boostu – z režimu nebo tlačítkem
  - id: heating_boost_start
    alias: "Topení: start Boostu (nastav boost_until)"
    mode: restart # Nový podnět ruší předchozí běh

    # 🛎️ Spouštěče
    triggers:
      - trigger: state
        entity_id: input_select.topny_rezim
        to: "Boost" # Přepnuto na Boost
      - trigger: state
        entity_id: input_boolean.boost_now
        to: "on" # Ruční „Boost nyní“

    # ⚙️ Akce
    action:
      - variables:
          minutes: "{{ states('input_number.boost_minutes') | int(60) }}" # Doba trvání

      - action: input_datetime.set_datetime
        target:
          entity_id: input_datetime.boost_until
        data:
          datetime: "{{ (now() + timedelta(minutes=minutes)).isoformat() }}" # Teď + minutes

  # ⏹ Konec Boostu – automaticky zhasni tlačítko po vypršení
  - id: heating_boost_auto_clear_button
    alias: "Topení: po vypršení Boostu vypnout tlačítko"
    mode: queued # Bez kolizí při opakování

    # 🛎️ Spouštěče
    triggers:
      - trigger: time_pattern
        minutes: "/1" # Kontrola každou minutu
    condition:
      - condition: template
        value_template: >
          {% set until = states('input_datetime.boost_until') %}
          {% set uts   = as_timestamp(until, default=0) %}
          {{ is_state('input_boolean.boost_now','on') and now().timestamp() > uts }}  # Boost prošel?
    action:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.boost_now # Synchronizace UI se stavem
