# =====================================================================
# 🧠 SOUBOR: /config/heating/control/mode_logic.yaml
# =====================================================================
# 🎛️ Logika přepínání režimů topení (Auto / Eco / Boost / Off)
# -------------------------------------------------------------
# Co TENTO soubor dělá:
#  - Sleduje změnu input_select.topny_rezim
#  - Pro "Off" okamžitě vypne relé kotle (Aqara T2)
#  - Zapíše událost do Logbooku pro přehled
#
# Co TENTO soubor NEDĚLÁ (záměrně):
#  - Neovládá žádný binary_sensor (nejde to) – blokace Off se dělá v mode_engine.yaml
#  - Nepřepisuje prahy input_number.kotel_min_* – účinné prahy počítá mode_engine.yaml
#  - Neřeší Boost tlačítko / časování – to je v mode_engine.yaml (aby nebyly duplicity)
# =====================================================================

automation:
  - alias: "Topení – logika režimů (čistá)"
    id: heating_mode_logic_clean
    description: "Reaguje na změnu režimu. Pro Off vypne kotel; ostatní režimy nechává na mode_engine."
    mode: restart

    # 🛎️ Spouštěč: kdykoli se změní zvolený režim (Auto / Eco / Boost / Off)
    trigger:
      - platform: state
        entity_id: input_select.topny_rezim

    action:
      - choose:

          # ========================================================
          # 🔻 REŽIM OFF – kompletní vypnutí topení
          #  - Okamžitě vypne Aqara T2 relé (kotel)
          #  - Blokace kotle se současně projeví i v binary_sensor.kotel_mode_off_block
          #    (ten se vyhodnocuje v mode_engine.yaml z režimu a master přepínače)
          # ========================================================
          - conditions:
              - condition: state
                entity_id: input_select.topny_rezim
                state: "Off"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.aqara_lumi_switch_acn047_spinac

              - service: logbook.log
                data:
                  name: "Topení – režimy"
                  message: "Režim přepnut na Off → kotel vypnut."
                  entity_id: switch.aqara_lumi_switch_acn047_spinac

          # ========================================================
          # 🔸 REŽIM AUTO – standardní provoz
          #  - Nic aktivně nenastavujeme: účinné prahy řeší mode_engine.yaml
          # ========================================================
          - conditions:
              - condition: state
                entity_id: input_select.topny_rezim
                state: "Auto"
            sequence:
              - service: logbook.log
                data:
                  name: "Topení – režimy"
                  message: "Režim Auto → používají se účinné prahy z mode_engine."
                  entity_id: input_select.topny_rezim

          # ========================================================
          # 🌿 REŽIM ECO – úspornější
          #  - Nic aktivně nenastavujeme: zpřísnění prahů řeší mode_engine.yaml
          # ========================================================
          - conditions:
              - condition: state
                entity_id: input_select.topny_rezim
                state: "Eco"
            sequence:
              - service: logbook.log
                data:
                  name: "Topení – režimy"
                  message: "Režim Eco → přísnější účinné prahy (mode_engine)."
                  entity_id: input_select.topny_rezim

          # ========================================================
          # ⚡ REŽIM BOOST – krátkodobé „přitop“
          #  - Nic aktivně nenastavujeme: boost_until a auto-ukončení řeší mode_engine.yaml
          # ========================================================
          - conditions:
              - condition: state
                entity_id: input_select.topny_rezim
                state: "Boost"
            sequence:
              - service: logbook.log
                data:
                  name: "Topení – režimy"
                  message: "Režim Boost → uvolněné účinné prahy + časování (mode_engine)."
                  entity_id: input_select.topny_rezim
