# YAML 2024.10
# =====================================================================
# 🧠 /config/heating/control/mode_boost.yaml – BOOST LOGIKA (only)
# =====================================================================

template:
  # ── BOOST aktivní? (režim Boost NEBO tlačítko NEBO do-času) ────────
  - binary_sensor:
      - name: "kotel_boost_active"
        unique_id: kotel_boost_active
        device_class: heat

        # ✅ Senzor je dostupný až když jsou dostupné všechny vstupy
        availability: >-
          {{ states('input_select.topny_rezim') not in ['unknown','unavailable','']
             and states('input_boolean.boost_now') not in ['unknown','unavailable','']
             and states('input_datetime.boost_until') not in ['unknown','unavailable',''] }}

        # ✅ ON když: režim Boost, tlačítko ON, nebo boost_until v budoucnu
        state: >-
          {% set mode = states('input_select.topny_rezim') %}
          {% set btn  = is_state('input_boolean.boost_now','on') %}
          {% set uts  = as_timestamp(states('input_datetime.boost_until'), default=0) %}
          {{ mode == 'Boost' or btn or (now().timestamp() < uts) }}

        attributes:
          until: "{{ states('input_datetime.boost_until') }}"
          remaining_min: >-
            {% set uts = as_timestamp(states('input_datetime.boost_until'), default=0) %}
            {% set rem = (uts - now().timestamp()) / 60 %}
            {{ rem|round(0) if rem > 0 else 0 }}


# =====================================================================
# 🤖 AUTOMATIZACE PRO BOOST
# =====================================================================
automation:

  # ▶️ Start Boostu – z režimu nebo tlačítkem → nastav boost_until
  - id: heating_boost_start
    alias: "Topení: start Boostu (nastav boost_until)"
    mode: restart
    triggers:
      - trigger: state
        entity_id: input_select.topny_rezim
        to: "Boost"
      - trigger: state
        entity_id: input_boolean.boost_now
        to: "on"
    actions:
      - variables:
          minutes: "{{ states('input_number.boost_minutes') | int(60) }}"
      - action: input_datetime.set_datetime
        target:
          entity_id: input_datetime.boost_until
        data:
          datetime: "{{ (now() + timedelta(minutes=minutes)).isoformat() }}"

  # ⚡ Boost ON → nastav komfortní setpointy (poslední komfort + offset)
  - id: heating_boost_apply_comfort_on
    alias: "Boost: při startu nastav komfort do zón"
    mode: restart

    triggers:
      - trigger: state
        entity_id: binary_sensor.kotel_boost_active
        to: "on"

    conditions:
      - condition: state
        entity_id: input_boolean.topny_system_enable
        state: "on"
      - condition: state
        entity_id: binary_sensor.kotel_mode_off_block
        state: "off"

    variables:
      boost_offset: "{{ states('input_number.boost_comfort_offset_c')|float(0) }}"
      # zde definujeme zóny + jejich "last comfort" helper
      zones: >
        {{ [
          dict(name='Přízemí – Michal', climate='climate.prizemi_michal', last='input_number.prizemi_michal_last_comfort'),
          dict(name='1. patro – Kuchyň', climate='climate.1p_jidelna',    last='input_number.1p_jidelna_last_comfort'),
          dict(name='2. patro – Máma',  climate='climate.2p_mama',        last='input_number.2p_mama_last_comfort')
        ] }}

    actions:
      - repeat:
          for_each: "{{ zones }}"
          sequence:
            - variables:
                climate: "{{ repeat.item.climate }}"
                last: "{{ repeat.item.last }}"
                # Základ komfortu: preferuj input_number.*_last_comfort, když by byl unknown → vem aktuální setpoint
                comfort_base: >-
                  {% set v = states(last) %}
                  {% if v not in ['unknown','unavailable',''] %}{{ v|float }}
                  {% else %}{{ state_attr(climate,'temperature')|float(21) }}
                  {% endif %}
                tmin: "{{ state_attr(climate,'min_temp')|float(5) }}"
                tmax: "{{ state_attr(climate,'max_temp')|float(30) }}"
                raw_target: "{{ (comfort_base + boost_offset)|float }}"
                target: >-
                  {% set x = raw_target|float %}
                  {% if x < tmin %}{{ tmin }}
                  {% elif x > tmax %}{{ tmax }}
                  {% else %}{{ x }}
                  {% endif %}

            - action: climate.set_temperature
              target:
                entity_id: "{{ climate }}"
              data:
                temperature: "{{ target|round(1) }}"

            - action: logbook.log
              data:
                name: "Boost → {{ repeat.item.name }}"
                message: "Cíl {{ target|round(1) }} °C (zdroj={{ last }}, offset={{ boost_offset }})"
                entity_id: "{{ climate }}"

  # ⏹ Každou minutu hlídej vypršení → zhasni tlačítko
  - id: heating_boost_auto_clear_button
    alias: "Topení: po vypršení Boostu vypnout tlačítko"
    mode: queued
    triggers:
      - trigger: time_pattern
        minutes: "/1"
    conditions:
      - condition: template
        value_template: >-
          {% set uts = as_timestamp(states('input_datetime.boost_until'), default=0) %}
          {{ is_state('input_boolean.boost_now','on') and now().timestamp() > uts }}
    actions:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.boost_now

  # 🔁 Boost OFF → reapply schedule (pokud používáš END akce rozvrhů)
  - id: heating_boost_reapply_schedule_off
    alias: "Boost: po skončení znovu aplikuj rozvrh"
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.kotel_boost_active
        to: "off"
    actions:
      - action: automation.trigger
        target:
          entity_id:
            - automation.sched_prizemi_michal_end
            - automation.sched_1p_jidelna_end
            - automation.sched_2p_mama_end
