# =====================================================================
# Soubor   : config/heating/control/mode_boost.yaml
# Modul    : Topení – logika režimu BOOST
# Účel     : Výpočet stavu Boost, nastavení komfortu a návrat k rozvrhům
# Autor    : Michal
# Poslední úprava : 2025-11-19
# Poznámka : YAML syntaxe podle HA 2024.10 (triggers / conditions / actions)
# =====================================================================

# =====================================================================
# TEMPLATE – BOOST STAV
# =====================================================================
template:
  - binary_sensor:
      # -----------------------------------------------------------------
      # SENSOR: Boost aktivní? (režim Boost / tlačítko / čas boost_until)
      # Logika:
      # - dostupný jen pokud jsou dostupné všechny vstupy
      # - ON pokud je režim Boost, tlačítko ON nebo boost_until v budoucnu
      # -----------------------------------------------------------------
      - name: "kotel_boost_active"
        unique_id: kotel_boost_active
        device_class: heat

        # Senzor je dostupný až když jsou dostupné všechny vstupy
        availability: >-
          {{ states('input_select.topny_rezim') not in ['unknown','unavailable','']
             and states('input_boolean.boost_now') not in ['unknown','unavailable','']
             and states('input_datetime.boost_until') not in ['unknown','unavailable',''] }}

        # ON když: režim Boost, tlačítko ON, nebo boost_until v budoucnu
        state: >-
          {% set mode = states('input_select.topny_rezim') %}
          {% set btn  = is_state('input_boolean.boost_now','on') %}
          {% set uts  = as_timestamp(states('input_datetime.boost_until'), default=0) %}
          {{ mode == 'Boost' or btn or (now().timestamp() < uts) }}

        attributes:
          until: "{{ states('input_datetime.boost_until') }}"
          remaining_min: >-
            {% set uts = as_timestamp(states('input_datetime.boost_until'), default=0) %}
            {% set rem = (uts - now().timestamp()) / 60 %}
            {{ rem|round(0) if rem > 0 else 0 }}

# =====================================================================
# AUTOMATIZACE – BOOST LOGIKA
# =====================================================================
automation:

  # -------------------------------------------------------------------
  # AUTOMATIZACE: Start Boostu → nastavit boost_until
  # Logika:
  # - při přepnutí režimu na Boost nebo stisku tlačítka Boost
  # - spočítá dobu boostu z input_number.boost_minutes
  # - nastaví input_datetime.boost_until
  # -------------------------------------------------------------------
  - alias: "Topení: start Boostu (nastav boost_until)"
    id: heating_boost_start
    description: >
      Start Boostu z režimu nebo tlačítka. Spočítá dobu boostu v minutách
      a nastaví čas ukončení do input_datetime.boost_until.
    mode: restart

    triggers:
      - trigger: state
        entity_id: input_select.topny_rezim
        to: "Boost"
      - trigger: state
        entity_id: input_boolean.boost_now
        to: "on"

    conditions: []

    actions:
      - variables:
          minutes: "{{ states('input_number.boost_minutes') | int(60) }}"
      - action: input_datetime.set_datetime
        target:
          entity_id: input_datetime.boost_until
        data:
          datetime: "{{ (now() + timedelta(minutes=minutes)).isoformat() }}"

  # -------------------------------------------------------------------
  # AUTOMATIZACE: Boost ON → nastavit komfortní setpointy v zónách
  # Logika:
  # - při aktivaci Boostu nastaví v zónách komfortní teplotu
  # - základ je last_comfort nebo aktuální setpoint
  # - přičte offset z input_number.boost_comfort_offset_c
  # - ořízne do min/max rozsahu klimatizace
  # -------------------------------------------------------------------
  - alias: "Boost: při startu nastav komfort do zón"
    id: heating_boost_apply_comfort_on
    description: >
      Při aktivaci Boostu nastaví komfortní teplotu v jednotlivých zónách
      podle posledního komfortu a zadaného offsetu.
    mode: restart

    triggers:
      - trigger: state
        entity_id: binary_sensor.kotel_boost_active
        to: "on"

    conditions:
      - condition: state
        entity_id: input_boolean.topny_system_enable
        state: "on"
      - condition: state
        entity_id: binary_sensor.kotel_mode_off_block
        state: "off"

    variables:
      boost_offset: "{{ states('input_number.boost_comfort_offset_c')|float(0) }}"
      # Zde definujeme zóny + jejich "last comfort" helper
      zones: >
        {{ [
          dict(name='Sklep – Michal', climate='climate.sklep_michal', last='input_number.sklep_michal_last_comfort'),
          dict(name='Přízemí – Michal', climate='climate.prizemi_michal', last='input_number.prizemi_michal_last_comfort'),
          dict(name='Přízemí – Chodba zachod', climate='climate.prizemi_chodba_zachod', last='input_number.prizemi_chodba_zachod_last_comfort'),
          dict(name='1. patro – Jídelna', climate='climate.1p_jidelna', last='input_number.1p_jidelna_last_comfort'),
          dict(name='1. patro – Kuchyň', climate='climate.1p_kuchyn', last='input_number.1p_kuchyn_last_comfort'),
          dict(name='1. patro – Koupelna', climate='climate.1p_koupelna', last='input_number.1p_koupelna_last_comfort'),
          dict(name='1. patro – Chodba', climate='climate.1p_chodba', last='input_number.1p_chodba_last_comfort'),
          dict(name='2. patro – Máma',  climate='climate.2p_mama', last='input_number.2p_mama_last_comfort')
        ] }}

    actions:
      - repeat:
          for_each: "{{ zones }}"
          sequence:
            - variables:
                climate: "{{ repeat.item.climate }}"
                last: "{{ repeat.item.last }}"
                # Základ komfortu: preferuj input_number.*_last_comfort,
                # když je unknown/unavailable → vezmi aktuální setpoint
                comfort_base: >-
                  {% set v = states(last) %}
                  {% if v not in ['unknown','unavailable',''] %}{{ v|float }}
                  {% else %}{{ state_attr(climate,'temperature')|float(21) }}
                  {% endif %}
                tmin: "{{ state_attr(climate,'min_temp')|float(5) }}"
                tmax: "{{ state_attr(climate,'max_temp')|float(30) }}"
                raw_target: "{{ (comfort_base + boost_offset)|float }}"
                target: >-
                  {% set x = raw_target|float %}
                  {% if x < tmin %}{{ tmin }}
                  {% elif x > tmax %}{{ tmax }}
                  {% else %}{{ x }}
                  {% endif %}

            - action: climate.set_temperature
              target:
                entity_id: "{{ climate }}"
              data:
                temperature: "{{ target|round(1) }}"

            - action: logbook.log
              data:
                name: "Boost → {{ repeat.item.name }}"
                message: "Cíl {{ target|round(1) }} °C (zdroj={{ last }}, offset={{ boost_offset }})"
                entity_id: "{{ climate }}"

  # -------------------------------------------------------------------
  # AUTOMATIZACE: Po vypršení Boostu vypnout tlačítko
  # Logika:
  # - každou minutu kontroluje, zda už boost_until vypršel
  # - pokud ano a tlačítko je stále ON → vypne ho
  # -------------------------------------------------------------------
  - alias: "Topení: po vypršení Boostu vypnout tlačítko"
    id: heating_boost_auto_clear_button
    description: >
      Hlídá vypršení času Boostu podle boost_until. Pokud čas vypršel
      a tlačítko Boost je stále zapnuté, automaticky ho vypne.
    mode: queued

    triggers:
      - trigger: time_pattern
        minutes: "/1"

    conditions:
      - condition: template
        value_template: >-
          {% set uts = as_timestamp(states('input_datetime.boost_until'), default=0) %}
          {{ is_state('input_boolean.boost_now','on') and now().timestamp() > uts }}

    actions:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.boost_now

  # -------------------------------------------------------------------
  # AUTOMATIZACE: Po skončení Boostu znovu aplikovat rozvrhy
  # Logika:
  # - při přechodu kotel_boost_active z ON na OFF
  # - znovu spustí "END" automatizace všech zón pro návrat k rozvrhům
  # -------------------------------------------------------------------
  - alias: "Boost: po skončení znovu aplikuj rozvrh"
    id: heating_boost_reapply_schedule_off
    description: >
      Po skončení Boostu znovu spustí koncové automatizace rozvrhů
      ve všech zónách, aby se obnovilo plánované řízení teploty.
    mode: restart

    triggers:
      - trigger: state
        entity_id: binary_sensor.kotel_boost_active
        to: "off"

    conditions: []

    actions:
      - action: automation.trigger
        target:
          entity_id:
            - automation.schedule_prizemi_michal_smart
            - automation.schedule_1p_jidelna_smart
            - automation.schedule_2p_mama_smart