# =====================================================================
# Soubor   : config/heating/schedule/automation/smart/smart_1p_jidelna.yaml
# Modul    : Rozvrh 1P Jídelna – inteligentní spouštění
# Účel     : Chytré spouštění komfort/ECO podle časového okna a last_comfort
#           (v režimu Eco drží globální ECO teplotu mimo rozvrh)
# Autor    : Michal
# Poslední úprava : 2025-11-19
# Poznámka : Minimalizuje zbytečné přepisování setpointu a spam v logbooku
# =====================================================================

automation:
  # ===================================================================
  # SEKCE: Rozvrh 1P Jídelna – inteligentní spouštění
  # ===================================================================
  - alias: "Rozvrh 1P Jídelna – inteligentní spouštění"
    id: schedule_1p_jidelna_smart
    description: >
      Inteligentně spíná komfortní nebo ECO teplotu v zóně 1P Jídelna
      pouze při smysluplných změnách (čas start/konec, úprava rozvrhu,
      změna last_comfort, ruční zásah do hlavice).
    mode: restart
    initial_state: true

    # ---------------------------------------------------------------
    # TRIGGERY – reagujeme jen na „velké“ změny, ne na minutové tiky
    # ---------------------------------------------------------------
    triggers:
      # Časové body: začátky a konce pro každý den v týdnu
      - trigger: time
        at:
          - input_datetime.1p_jidelna_monday_start
          - input_datetime.1p_jidelna_monday_end
          - input_datetime.1p_jidelna_tuesday_start
          - input_datetime.1p_jidelna_tuesday_end
          - input_datetime.1p_jidelna_wednesday_start
          - input_datetime.1p_jidelna_wednesday_end
          - input_datetime.1p_jidelna_thursday_start
          - input_datetime.1p_jidelna_thursday_end
          - input_datetime.1p_jidelna_friday_start
          - input_datetime.1p_jidelna_friday_end
          - input_datetime.1p_jidelna_saturday_start
          - input_datetime.1p_jidelna_saturday_end
          - input_datetime.1p_jidelna_sunday_start
          - input_datetime.1p_jidelna_sunday_end

      # Změna nastavení rozvrhu (časy nebo enable flag)
      - trigger: state
        entity_id:
          - input_datetime.1p_jidelna_monday_start
          - input_datetime.1p_jidelna_monday_end
          - input_datetime.1p_jidelna_tuesday_start
          - input_datetime.1p_jidelna_tuesday_end
          - input_datetime.1p_jidelna_wednesday_start
          - input_datetime.1p_jidelna_wednesday_end
          - input_datetime.1p_jidelna_thursday_start
          - input_datetime.1p_jidelna_thursday_end
          - input_datetime.1p_jidelna_friday_start
          - input_datetime.1p_jidelna_friday_end
          - input_datetime.1p_jidelna_saturday_start
          - input_datetime.1p_jidelna_saturday_end
          - input_datetime.1p_jidelna_sunday_start
          - input_datetime.1p_jidelna_sunday_end
          - input_boolean.schedule_enable_1p_jidelna
          - input_select.topny_rezim

      # Změna „poslední komfortní teploty“ v HA → reapply, pokud jsme v okně
      - trigger: state
        entity_id: input_number.1p_jidelna_last_comfort

      # Ruční změna setpointu na hlavici → reaguj podle toho, zda jsme v okně
      - trigger: state
        entity_id: climate.1p_jidelna
        attribute: temperature

    # ---------------------------------------------------------------
    # PROMĚNNÉ – teploty + volba správných časů podle dne v týdnu
    # ---------------------------------------------------------------
    variables:
      mode: "{{ states('input_select.topny_rezim') }}"
      eco_temp: "{{ states('input_number.eco_temp_default') | float(15) }}"
      last_comfort: "{{ states('input_number.1p_jidelna_last_comfort') | float(22) }}"

      # Výběr START podle aktuálního dne (0=Po .. 6=Ne)
      start: >
        {% set d = now().weekday() %}
        {% if   d == 0 %} {{ states('input_datetime.1p_jidelna_monday_start') }}
        {% elif d == 1 %} {{ states('input_datetime.1p_jidelna_tuesday_start') }}
        {% elif d == 2 %} {{ states('input_datetime.1p_jidelna_wednesday_start') }}
        {% elif d == 3 %} {{ states('input_datetime.1p_jidelna_thursday_start') }}
        {% elif d == 4 %} {{ states('input_datetime.1p_jidelna_friday_start') }}
        {% elif d == 5 %} {{ states('input_datetime.1p_jidelna_saturday_start') }}
        {% else %}         {{ states('input_datetime.1p_jidelna_sunday_start') }}
        {% endif %}

      # Výběr END podle aktuálního dne
      end: >
        {% set d = now().weekday() %}
        {% if   d == 0 %} {{ states('input_datetime.1p_jidelna_monday_end') }}
        {% elif d == 1 %} {{ states('input_datetime.1p_jidelna_tuesday_end') }}
        {% elif d == 2 %} {{ states('input_datetime.1p_jidelna_wednesday_end') }}
        {% elif d == 3 %} {{ states('input_datetime.1p_jidelna_thursday_end') }}
        {% elif d == 4 %} {{ states('input_datetime.1p_jidelna_friday_end') }}
        {% elif d == 5 %} {{ states('input_datetime.1p_jidelna_saturday_end') }}
        {% else %}         {{ states('input_datetime.1p_jidelna_sunday_end') }}
        {% endif %}

      now_hms: "{{ now().strftime('%H:%M:%S') }}"

      # Jsme uvnitř okna? (umí i interval přes půlnoc, když start > end)
      in_window: >
        {% set s = start %}
        {% set e = end %}
        {% set n = now_hms %}

        {# Když nemáme validní časy, bereme to jako MIMO okno #}
        {% if s in ['', 'unknown', 'unavailable'] or e in ['', 'unknown', 'unavailable'] %}
          false
        {% elif s <= e %}
          {{ s <= n < e }}
        {% else %}
          {{ (n >= s) or (n < e) }}
        {% endif %}

    # ---------------------------------------------------------------
    # PODMÍNKY – globální enable rozvrhu pro 1P Jídelna
    # ---------------------------------------------------------------
    conditions:
      - condition: state
        entity_id: input_boolean.schedule_enable_1p_jidelna
        state: "on"

    # ---------------------------------------------------------------
    # AKCE – logika režimů + komfort/ECO podle okna
    # ---------------------------------------------------------------
    actions:
      # Debounce: pokud to spustila hlavice, počkej, aby capture stihl uložit last_comfort
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{ trigger.platform == 'state'
                     and trigger.entity_id == 'climate.1p_jidelna' }}
            sequence:
              - delay: "00:00:01"

      - choose:
          # ==========================================================
          # REŽIM ECO → vždy nastav ECO teplotu (ignoruje rozvrhové okno)
          # ==========================================================
          - conditions:
              - condition: template
                value_template: "{{ mode == 'Eco' }}"
            sequence:
              - action: climate.set_hvac_mode
                target:
                  entity_id: climate.1p_jidelna
                data:
                  hvac_mode: heat

              - condition: template
                value_template: >
                  {{ ((state_attr('climate.1p_jidelna','temperature') | float)
                      - (eco_temp | float)) | abs > 0.1 }}

              - action: climate.set_temperature
                target:
                  entity_id: climate.1p_jidelna
                data:
                  temperature: "{{ eco_temp }}"

              - action: logbook.log
                data:
                  name: "Rozvrh 1P Jídelna"
                  message: "Globální ECO režim – cílová teplota {{ eco_temp }} °C"
                  entity_id: climate.1p_jidelna

          # ==========================================================
          # REŽIM Auto / Boost → komfort v okně, ECO mimo okno
          # ==========================================================
          - conditions:
              - condition: template
                value_template: "{{ mode in ['Auto', 'Boost'] }}"
            sequence:
              - choose:
                  # V OKNĚ → nastav POSLEDNÍ KOMFORT
                  - conditions:
                      - condition: template
                        value_template: "{{ in_window }}"
                    sequence:
                      - action: climate.set_hvac_mode
                        target:
                          entity_id: climate.1p_jidelna
                        data:
                          hvac_mode: heat

                      - condition: template
                        value_template: >
                          {{ ((state_attr('climate.1p_jidelna','temperature') | float)
                              - (last_comfort | float)) | abs > 0.1 }}

                      - action: climate.set_temperature
                        target:
                          entity_id: climate.1p_jidelna
                        data:
                          temperature: "{{ last_comfort }}"

                      - action: logbook.log
                        data:
                          name: "Rozvrh 1P Jídelna"
                          message: "Komfortní režim {{ last_comfort }} °C (inteligentní spuštění)"
                          entity_id: climate.1p_jidelna

                  # MIMO OKNO → nastav ECO
                  - conditions:
                      - condition: template
                        value_template: "{{ not in_window }}"
                    sequence:
                      - action: climate.set_hvac_mode
                        target:
                          entity_id: climate.1p_jidelna
                        data:
                          hvac_mode: heat

                      - condition: template
                        value_template: >
                          {{ ((state_attr('climate.1p_jidelna','temperature') | float)
                              - (eco_temp | float)) | abs > 0.1 }}

                      - action: climate.set_temperature
                        target:
                          entity_id: climate.1p_jidelna
                        data:
                          temperature: "{{ eco_temp }}"

                      - action: logbook.log
                        data:
                          name: "Rozvrh 1P Jídelna"
                          message: "ECO {{ eco_temp }} °C (inteligentní spuštění)"
                          entity_id: climate.1p_jidelna

          # ==========================================================
          # REŽIM Off → rozvrh nic nepřepisuje, jen logne stav
          # ==========================================================
          - conditions:
              - condition: template
                value_template: "{{ mode == 'Off' }}"
            sequence:
              - action: logbook.log
                data:
                  name: "Rozvrh 1P Jídelna"
                  message: "Režim Off – rozvrh nemění cílovou teplotu."
                  entity_id: climate.1p_jidelna