# =====================================================================
# Soubor   : config/heating/follow_user/capture/follow_2p_mama_capture.yaml
# Modul    : Zachytávání uživatelských setpointů – 2. patro Máma
# Účel     : Ukládání poslední ručně nastavené teploty z hlavice do helperu
# Autor    : Michal
# Poslední úprava : 2025-11-19
# Poznámka : Sleduje změnu setpointu + inicializace po startu HA
# =====================================================================

automation:
  # ===================================================================
  # SEKCE: Zóna 2P Máma – zachytávání setpointu
  # ===================================================================

  # -------------------------------------------------------------------
  # AUTOMATIZACE: Zachytit změnu setpointu na hlavici
  # Logika:
  # - reaguje na jakýkoliv state change climate.2p_mama
  # - přečte novou cílovou teplotu (temperature)
  # - pokud > 0 (platná), uloží do input_number.zona_2p_mama_user_set_temp
  # -------------------------------------------------------------------
  - alias: "Zóna – 2. patro Máma: zachyť změnu setpointu"
    id: zona_2p_mama_capture_setpoint
    description: >
      Zachytává ruční změnu cílové teploty z hlavice climate.2p_mama
      a ukládá ji jako poslední uživatelský setpoint.
    mode: restart

    triggers:
      - trigger: state
        entity_id: climate.2p_mama

    variables:
      new_sp: "{{ state_attr('climate.2p_mama','temperature') | float(0) }}"

    conditions:
      - condition: template
        value_template: "{{ new_sp > 0 }}"

    actions:
      - action: input_number.set_value
        target:
          entity_id: input_number.zona_2p_mama_user_set_temp
        data:
          value: "{{ new_sp }}"

  # -------------------------------------------------------------------
  # AUTOMATIZACE: Inicializace helperu po startu HA
  # Logika:
  # - po startu HA načte aktuální setpoint z hlavice
  # - uloží jej do input_number.zona_2p_mama_user_set_temp
  # - malé zpoždění (5s) kvůli inicializaci Zigbee zařízení
  # -------------------------------------------------------------------
  - alias: "Zóna – 2. patro Máma: init helperu po startu"
    id: zona_2p_mama_init_on_start
    description: >
      Po restartu Home Assistantu nastaví výchozí hodnotu helperu
      podle aktuální teploty v hlavici climate.2p_mama.
    mode: single

    triggers:
      - trigger: homeassistant
        event: start

    conditions: []

    actions:
      - delay: "00:00:05"

      - variables:
          sp: "{{ state_attr('climate.2p_mama','temperature') | float(22.0) }}"

      - action: input_number.set_value
        target:
          entity_id: input_number.zona_2p_mama_user_set_temp
        data:
          value: "{{ sp }}"
