# =====================================================================
# Soubor   : config/heating/follow_user/capture/follow_prizemi_michal_capture.yaml
# Modul    : Zachytávání uživatelských setpointů – Přízemí Michal
# Účel     : Ukládání poslední ručně nastavené teploty z hlavice do helperu
# Autor    : Michal
# Poslední úprava : 2025-11-19
# Poznámka : Sleduje změny setpointu + inicializace po startu HA
# =====================================================================

automation:
  # ===================================================================
  # SEKCE: Zóna Přízemí Michal – zachytávání setpointu
  # ===================================================================

  # -------------------------------------------------------------------
  # AUTOMATIZACE: Zachytit změnu setpointu na hlavici
  # Logika:
  # - reaguje na každou změnu climate.prizemi_michal
  # - načte aktuální cílovou teplotu (temperature)
  # - pokud je hodnota > 0, uloží do helperu input_number.*
  # -------------------------------------------------------------------
  - alias: "Zóna – Přízemí Michal: zachyť změnu setpointu"
    id: zona_prizemi_michal_capture_setpoint
    description: >
      Zachytává změnu cílové teploty z hlavice climate.prizemi_michal
      a ukládá ji jako poslední ručně nastavenou hodnotu.
    mode: restart

    triggers:
      - trigger: state
        entity_id: climate.prizemi_michal

    variables:
      new_sp: "{{ state_attr('climate.prizemi_michal','temperature') | float(0) }}"

    conditions:
      - condition: template
        value_template: "{{ new_sp > 0 }}"

    actions:
      - action: input_number.set_value
        target:
          entity_id: input_number.zona_prizemi_michal_user_set_temp
        data:
          value: "{{ new_sp }}"

  # -------------------------------------------------------------------
  # AUTOMATIZACE: Inicializace helperu po startu HA
  # Logika:
  # - při startu HA načte teplotu z hlavice climate.prizemi_michal
  # - uloží ji do helperu jako poslední známou uživatelskou hodnotu
  # - malé zpoždění kvůli Zigbee inicializaci
  # -------------------------------------------------------------------
  - alias: "Zóna – Přízemí Michal: init helperu po startu"
    id: zona_prizemi_michal_init_on_start
    description: >
      Po restartu Home Assistantu nastaví výchozí hodnotu helperu
      podle aktuální teploty v hlavici climate.prizemi_michal.
    mode: single

    triggers:
      - trigger: homeassistant
        event: start

    conditions: []

    actions:
      - delay: "00:00:05"

      - variables:
          sp: "{{ state_attr('climate.prizemi_michal','temperature') | float(22.0) }}"

      - action: input_number.set_value
        target:
          entity_id: input_number.zona_prizemi_michal_user_set_temp
        data:
          value: "{{ sp }}"
